// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAauAM6LaZx3m0ilj1pMzn16gJoXMNmWrw',
    appId: '1:527520411313:web:b421378aa13b7573b53c90',
    messagingSenderId: '527520411313',
    projectId: 'todo-flutter-349512',
    authDomain: 'todo-flutter-349512.firebaseapp.com',
    databaseURL: 'https://todo-flutter-349512-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-349512.appspot.com',
    measurementId: 'G-2EHLYYWLXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8hfTtLBvnl1-JLExRk_plmKhcSQpD9Q',
    appId: '1:527520411313:android:f3c4a35abf925a96b53c90',
    messagingSenderId: '527520411313',
    projectId: 'todo-flutter-349512',
    databaseURL: 'https://todo-flutter-349512-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-349512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmC4PymUOLAftChJSp759K2DIipptsk_U',
    appId: '1:527520411313:ios:833860bc63b9fe92b53c90',
    messagingSenderId: '527520411313',
    projectId: 'todo-flutter-349512',
    databaseURL: 'https://todo-flutter-349512-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-349512.appspot.com',
    iosClientId: '527520411313-c1ujjrtkjaqmluaok9rqbusg45l80j82.apps.googleusercontent.com',
    iosBundleId: 'com.github.aliva.todo',
  );
}
