name: Build
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        cache: true
    - run: flutter pub get
    - run: |
        echo ${{ secrets.KEY_PROPERTIES }} | base64 --decode > android/key.properties
        echo ${{ secrets.$KEY_JKS }} | base64 --decode > android/key.jks
    - run: flutter build apk --build-number=${GITHUB_RUN_ATTEMPT}
    - run: flutter build appbundle --build-number=${GITHUB_RUN_ATTEMPT}
    - uses: actions/upload-artifact@v3
      with:
        name: apk-files
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        cache: true
    - run: flutter pub get
    - run: flutter build web
    - uses: actions/upload-artifact@v3
      with:
        name: web-files
        path: |
          build/web/
  deploy-firebase:
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: web-files
          path: build/web/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODO_FLUTTER_349512 }}'
          channelId: live
          projectId: todo-flutter-349512
